ALTER TABLE pets ADD COLUMN health INTEGER NOT NULL DEFAULT 90;
ALTER TABLE pets ADD COLUMN mood INTEGER NOT NULL DEFAULT 70;
ALTER TABLE pets ADD COLUMN energy INTEGER NOT NULL DEFAULT 85;
ALTER TABLE pets ADD COLUMN xp INTEGER NOT NULL DEFAULT 0;
ALTER TABLE pets ADD COLUMN gold INTEGER NOT NULL DEFAULT 50;
ALTER TABLE pets ADD COLUMN is_sleeping INTEGER NOT NULL DEFAULT 0;
ALTER TABLE pets ADD COLUMN last_update_ms INTEGER NOT NULL DEFAULT 0;

UPDATE pets
SET last_update_ms = CAST(strftime('%s', 'now') AS INTEGER) * 1000
WHERE last_update_ms = 0;
